// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0xa4mno0tN6rc-xDlJvvtzzqD1XpxaUw',
    appId: '1:142209637999:web:2a4f1352ec7121d037379a',
    messagingSenderId: '142209637999',
    projectId: 'fundi-connect-af6ff',
    authDomain: 'fundi-connect-af6ff.firebaseapp.com',
    storageBucket: 'fundi-connect-af6ff.firebasestorage.app',
    measurementId: 'G-635RY8GVG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoPabV-XOcmrazeg4fWzLPoHvyTLmbuHM',
    appId: '1:142209637999:android:808e9144b1716f2d37379a',
    messagingSenderId: '142209637999',
    projectId: 'fundi-connect-af6ff',
    storageBucket: 'fundi-connect-af6ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-t8inr5zzgKyIvz0dqBHuinb0CUBq5cE',
    appId: '1:142209637999:ios:cd8735b18c0257d537379a',
    messagingSenderId: '142209637999',
    projectId: 'fundi-connect-af6ff',
    storageBucket: 'fundi-connect-af6ff.firebasestorage.app',
    iosBundleId: 'com.example.fundiConnect',
  );
}
